run:
  go: "1.24.0"

linters:
  enable-all: true
  disable:
    - wrapcheck
    - rowserrcheck
    - sqlclosecheck
    - wastedassign
    - varnamelen
    - tagliatelle
    - paralleltest
    - gci
    - cyclop
    - gocyclo
    - gocognit
    - gofumpt
    - nestif
    - lll
    - funlen
    - gochecknoglobals
    - interfacebloat
    - exhaustruct
    - godox
    - err113
    - testpackage
    - dupl
    - tenv

    - depguard
    - testifylint
    - musttag
    - staticcheck
    - ireturn
    - recvcheck
    - inamedparam
    - gosec
    - containedctx
    - copyloopvar

linters-settings:
  ireturn:
    allow:
      - anon
      - error
      - empty
      - stdlib
      - DriverDestinationInterface
      - DriverNotificationInterface
      - DriverSourceInterface
  gosec:
    excludes:
      - G204
  mnd:
    ignored-numbers:
      - "0o700"
    ignored-functions:
      - ParseInt
  nlreturn:
    block-size: 2
  gomoddirectives:
    replace-local: true
  revive:
    rules:
      - name: unused-parameter
        severity: warning
        disabled: true
