repos:
  - hooks:
      - entry: make swagger
        files: ^apps/stroltm?/internal/api
        id: swagger
        language: system
        name: swagger
        types_or: [go]

    repo: local
  # stroltm/ui
  - hooks:
      - always_run: true

        entry: make .lint-stroltm-ui
        id: stroltm/ui/typescript
        language: system
        name: stroltm/ui/typescript
    repo: local
  # strolt
  - hooks:
      - entry: make .lint-strolt
        files: ^apps/strolt
        id: strolt/lint
        language: system
        name: strolt/lint
        require_serial: true
        types: [text]
        types_or: [go]
      - entry: make .test-strolt
        files: ^apps/strolt
        id: strolt/test
        language: system
        name: strolt/test
        types: [text]
        types_or: [go]

    repo: local
  # stroltm
  - hooks:
      - entry: make .lint-stroltm
        files: ^apps/stroltm
        id: stroltm/lint
        language: system
        name: stroltm/lint
        require_serial: true
        types: [text]
        types_or: [go]
      - entry: make .test-stroltm
        files: ^apps/stroltm
        id: stroltm/test
        language: system
        name: stroltm/test
        types: [text]
        types_or: [go]

    repo: local
  - hooks:
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: end-of-file-fixer

    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
