exclude:
  - pnpm-lock.yaml
formatter:
  array_indent: 2
  eof_newline: true
  force_array_style: block
  force_quote_style: double
  indent: 2
  line_ending: lf
  pad_line_comments: 1
  retain_line_breaks_single: false
  trim_trailing_whitespace: true
  type: basic
