enableGlobalVirtualStore: true
enablePrePostScripts: false
hoistPattern: []
ignorePatchFailures: false
optimisticRepeatInstall: true
packages:
  - apps/*
  - website
  - apps/stroltm/ui
resolutionMode: lowest-direct
verifyDepsBeforeRun: install
