allowBuilds:
  "@nestjs/core": false
  "@openapitools/openapi-generator-cli": false
  "@swc/core": false
  core-js: false
  core-js-pure: false
  esbuild: false
audit: true
auditLevel: high
autoInstallPeers: true
blockExoticSubdeps: true
catalog:
  "@shibanet0/datamitsu-config": 0.1.7
dangerouslyAllowAllBuilds: false
dedupeDirectDeps: true
dedupePeerDependents: true
enableGlobalVirtualStore: true
enablePrePostScripts: false
engineStrict: true
hoistPattern: []
ignorePatchFailures: false
lockfile: true
minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - "@datamitsu/*"
  - "@ovineko/*"
  - "@shibanet0/*"
optimisticRepeatInstall: true
packageManagerStrict: true
packageManagerStrictVersion: true
packages:
  - apps/*
  - website
  - apps/stroltm/ui
preferFrozenLockfile: true
resolutionMode: lowest-direct
savePrefix: ""
strictDepBuilds: true
strictSsl: true
trustLockfile: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - detect-port@1.6.1
  - semver@6.3.1
  - undici-types@6.21.0
unsafePerm: false
updateNotifier: false
verifyDepsBeforeRun: install
verifyStoreIntegrity: true
