services:
  e2e:
    local:
      source:
        driver: local
        config:
          path: "/e2e/input"
      destinations:
        restic-local:
          extends: restic_base
          env:
            RESTIC_REPOSITORY: "s3:http://minio:9000/restic-local"
