destinations:
  destination_local:
    config:
      path: "./example/destination"
    driver: local # [local, restic]
# notifications:
#   slack:
#     driver: slack # [slack, telegram]

extendConfig:
  - ./notifications.yml
name: strolt
sources:
  source_local:
    config:
      path: "./example/source"
    driver: local # [local, mongodb, mysql, postgresql]
tasks:
  task_local:
    destinations:
      - destination_local
    notifications:
      - notification_slack
    schedule:
      backup: "*/1 * * * *"
      forget: "*/1 * * * *"
      prune: "*/1 * * * *"
    source: source_local
watchChanges: true # app will stop if config or secret files will changed
