formatters:
  enable:
  - gofmt
  - gofumpt
  - goimports
  - swaggo
linters:
  disable:
  - cyclop
  - dupl
  - err113
  - exhaustruct
  - funlen
  - gochecknoglobals
  - gochecknoinits
  - gocognit
  - goconst
  - godot
  - godox
  - goheader
  - gosmopolitan
  - ireturn
  - lll
  - maintidx
  - mnd
  - nestif
  - nlreturn
  - noinlineerr
  - nonamedreturns
  - paralleltest
  - tagliatelle
  - testpackage
  - varnamelen
  - wsl_v5
  enable:
  - arangolint
  - asasalint
  - asciicheck
  - bidichk
  - bodyclose
  - canonicalheader
  - clickhouselint
  - containedctx
  - contextcheck
  - copyloopvar
  - decorder
  - dogsled
  - dupword
  - durationcheck
  - embeddedstructfieldcheck
  - errcheck
  - errchkjson
  - errname
  - errorlint
  - exhaustive
  - exptostd
  - fatcontext
  - forcetypeassert
  - funcorder
  - ginkgolinter
  - gocheckcompilerdirectives
  - gochecksumtype
  - gocritic
  - gocyclo
  - godoclint
  - gomoddirectives
  - gomodguard_v2
  - goprintffuncname
  - gosec
  - govet
  - grouper
  - iface
  - importas
  - inamedparam
  - ineffassign
  - interfacebloat
  - intrange
  - iotamixing
  - loggercheck
  - makezero
  - mirror
  - misspell
  - modernize
  - musttag
  - nakedret
  - nilerr
  - nilnesserr
  - nilnil
  - noctx
  - nolintlint
  - nosprintfhostport
  - perfsprint
  - prealloc
  - predeclared
  - promlinter
  - protogetter
  - reassign
  - recvcheck
  - revive
  - rowserrcheck
  - sloglint
  - spancheck
  - sqlclosecheck
  - staticcheck
  - tagalign
  - testableexamples
  - testifylint
  - thelper
  - tparallel
  - unconvert
  - unparam
  - unqueryvet
  - unused
  - usestdlibvars
  - usetesting
  - wastedassign
  - whitespace
  - wrapcheck
  - zerologlint
  exclusions:
    rules:
    - linters:
      - noctx
      - errchkjson
      - forcetypeassert
      - dogsled
      path: "_test\\.go"
    - linters:
      - gocyclo
      - unparam
      path: "_test\\.go"
    - linters:
      - gosec
      path: "_test\\.go"
    - linters:
      - wrapcheck
      path: "_test\\.go"
  settings:
    gocyclo:
      min-complexity: 20
    revive:
      rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: empty-block
      - name: error-naming
      - name: error-return
      - name: error-strings
      - name: errorf
      - name: exported
      - name: increment-decrement
      - name: indent-error-flow
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: redefines-builtin-id
      - name: superfluous-else
      - name: time-naming
      - name: unexported-return
      - name: unreachable-code
      - name: var-declaration
      - name: var-naming
version: "2"
